### ISSUE TITLE
Logout

### ISSUE THREAD

**Issue by LBreda** [azate/laravel-telegram-login-auth#5]
Is it possible to logout, destroying the Telegram session on the client?

**Comment by hz61p1** [comment]
> Is it possible to logout, destroying the Telegram session on the client?
No, but you can shorten the session time on the Laravel side

**Comment by LBreda** [comment]
I'd like to destroy the Telegram session, to enforce the user to login again with his phone number. Now the user who logs out can login back with the "Login as" button without any authorization procedure.

**Comment by hz61p1** [comment]
You can try to create a new bot
