### ISSUE TITLE
NotAllRequiredAttributesException(missing last_name)

### ISSUE THREAD

**Issue by maxis55** [azate/laravel-telegram-login-auth#8]
Just letting you(and everyone else trying this package) know, that its not required to have last name on telegram, so validation that requires all attributes to be present fails since last name is not set, if you set it to null or empty string(at least on front-end) its still fails,
You should probably separate required and desired parameters, since only "hash" should be required

**Comment by Adizbek** [comment]
In addition user picture may not be present, as user can block displaying image.  Today I have encountered this problem.
